
window.GOONJ_VOICES=[
{id:"ur-PK-AsadNeural",language:"Urdu (Pakistan)",gender:"Male"},
{id:"en-US-AriaNeural",language:"English (US)",gender:"Female"},
{id:"en-US-JennyNeural",language:"English (US)",gender:"Female"},
{id:"en-US-GuyNeural",language:"English (US)",gender:"Male"},
{id:"en-GB-SoniaNeural",language:"English (UK)",gender:"Female"},
{id:"en-GB-RyanNeural",language:"English (UK)",gender:"Male"},
{id:"en-GB-LibbyNeural",language:"English (UK)",gender:"Female"},
{id:"en-GB-MaisieNeural",language:"English (UK)",gender:"Female"},
{id:"en-GB-ThomasNeural",language:"English (UK)",gender:"Male"},
{id:"en-IN-NeerjaNeural",language:"English (India)",gender:"Female"},
{id:"en-IN-PrabhatNeural",language:"English (India)",gender:"Male"},
{id:"en-AU-NatashaNeural",language:"English (Australia)",gender:"Female"},
{id:"en-AU-WilliamNeural",language:"English (Australia)",gender:"Male"},
{id:"en-CA-ClaraNeural",language:"English (Canada)",gender:"Female"},
{id:"en-CA-LiamNeural",language:"English (Canada)",gender:"Male"},
{id:"hi-IN-SwaraNeural",language:"Hindi (India)",gender:"Female"},
{id:"hi-IN-MadhurNeural",language:"Hindi (India)",gender:"Male"},
{id:"ar-SA-ZariyahNeural",language:"Arabic (Saudi)",gender:"Female"},
{id:"ar-SA-HamedNeural",language:"Arabic (Saudi)",gender:"Male"},
{id:"es-ES-ElviraNeural",language:"Spanish (Spain)",gender:"Female"},
{id:"es-ES-AlvaroNeural",language:"Spanish (Spain)",gender:"Male"},
{id:"fr-FR-DeniseNeural",language:"French (France)",gender:"Female"},
{id:"fr-FR-HenriNeural",language:"French (France)",gender:"Male"},
{id:"de-DE-KatjaNeural",language:"German (Germany)",gender:"Female"},
{id:"de-DE-ConradNeural",language:"German (Germany)",gender:"Male"},
{id:"it-IT-IsabellaNeural",language:"Italian (Italy)",gender:"Female"},
{id:"it-IT-DiegoNeural",language:"Italian (Italy)",gender:"Male"},
{id:"pt-BR-FranciscaNeural",language:"Portuguese (Brazil)",gender:"Female"},
{id:"pt-BR-AntonioNeural",language:"Portuguese (Brazil)",gender:"Male"},
{id:"ru-RU-SvetlanaNeural",language:"Russian (Russia)",gender:"Female"},
{id:"ru-RU-DmitryNeural",language:"Russian (Russia)",gender:"Male"},
{id:"ja-JP-NanamiNeural",language:"Japanese (Japan)",gender:"Female"},
{id:"ja-JP-KeitaNeural",language:"Japanese (Japan)",gender:"Male"},
{id:"zh-CN-XiaoxiaoNeural",language:"Chinese (Mandarin)",gender:"Female"},
{id:"zh-CN-YunxiNeural",language:"Chinese (Mandarin)",gender:"Male"},
{id:"ko-KR-SunHiNeural",language:"Korean (Korea)",gender:"Female"},
{id:"ko-KR-InJoonNeural",language:"Korean (Korea)",gender:"Male"},
{id:"tr-TR-EmelNeural",language:"Turkish (Turkey)",gender:"Female"},
{id:"tr-TR-AhmetNeural",language:"Turkish (Turkey)",gender:"Male"},
{id:"nl-NL-ColetteNeural",language:"Dutch (Netherlands)",gender:"Female"},
{id:"nl-NL-MaartenNeural",language:"Dutch (Netherlands)",gender:"Male"},
{id:"pl-PL-MarekNeural",language:"Polish (Poland)",gender:"Male"},
{id:"id-ID-GadisNeural",language:"Indonesian",gender:"Female"},
{id:"id-ID-ArdiNeural",language:"Indonesian",gender:"Male"},
{id:"ms-MY-YasminNeural",language:"Malay (Malaysia)",gender:"Female"},
{id:"ms-MY-OsmanNeural",language:"Malay (Malaysia)",gender:"Male"},
{id:"bn-IN-TanishaaNeural",language:"Bengali (India)",gender:"Female"},
{id:"bn-IN-BashkarNeural",language:"Bengali (India)",gender:"Male"},
{id:"ta-IN-PallaviNeural",language:"Tamil (India)",gender:"Female"},
{id:"ta-IN-ValluvarNeural",language:"Tamil (India)",gender:"Male"},
{id:"te-IN-ShrutiNeural",language:"Telugu (India)",gender:"Female"},
{id:"te-IN-MohanNeural",language:"Telugu (India)",gender:"Male"},
{id:"mr-IN-AarohiNeural",language:"Marathi (India)",gender:"Female"},
{id:"mr-IN-ManoharNeural",language:"Marathi (India)",gender:"Male"},
{id:"gu-IN-DhwaniNeural",language:"Gujarati (India)",gender:"Female"},
{id:"gu-IN-NiranjanNeural",language:"Gujarati (India)",gender:"Male"},
{id:"fa-IR-DilaraNeural",language:"Persian (Iran)",gender:"Female"},
{id:"fa-IR-FaridNeural",language:"Persian (Iran)",gender:"Male"},
{id:"uk-UA-PolinaNeural",language:"Ukrainian",gender:"Female"},
{id:"uk-UA-OstapNeural",language:"Ukrainian",gender:"Male"},
{id:"vi-VN-HoaiMyNeural",language:"Vietnamese",gender:"Female"},
{id:"vi-VN-NamMinhNeural",language:"Vietnamese",gender:"Male"},
{id:"th-TH-PremwadeeNeural",language:"Thai (Thailand)",gender:"Female"},
{id:"th-TH-NiwatNeural",language:"Thai (Thailand)",gender:"Male"}
];

